### ISSUE TITLE
Addressable LEDs

### ISSUE THREAD

**Issue by rgbpcb** [AcheronProject/AcheronSetup#2]
Should I connect pin 28 (PB15/SPI2_MOSI / "RGB_3V3") of the MCU directly to the DATA_INPUT pin of the first addressable RGB LED (SK6812 mini-E)?

Do I have to transform the voltage? How?

Maybe you could add a few addressable RGB LEDs as an example to the Joker PCB, so that I could move the LEDs, add more of them, and so on.

Thank you for this wonderful work!

**Comment by Gondolindrim** [comment]
Hi @rgbpcb !

Yes, you cannot connect pin 28 directly to a data input pin of the adressable LEDs because those work with a 5V logic whereas the MCU works with 3.3V. What you need essentially is a level translator. I recommend using TXS0101 . I can add this information to the Joker template.

**Comment by Gondolindrim** [comment]
Discussion continued in issue https://github.com/AcheronProject/AcheronSetup/issues/3 .
