### ISSUE TITLE
USB connector

### ISSUE THREAD

**Issue by rgbpcb** [AcheronProject/AcheronSetup#3]
How do I add a USB connector?

Do I understand correctly that the only thing that's missing in the Joker PCB in order to work are the "USB Connector" and "USB ESD" boxes that I can copy from the Athena schematic?

Maybe you could add a USB connector anywhere to the Joker PCB as an example, so that I can move it (and re-route the differential pair carefully).

Thank you and happy holidays!

**Comment by Gondolindrim** [comment]
Hi @rgbpcb !

It was just pointed out that it would be a good idea to indicate on the template how to connect the MCU to a USB and the LDO that steps 3.3V down from 5V. I will be adding those to the [joker article on the Acheron documentation](https://acheronproject.com/joker_mcus/joker/) .

**Comment by rgbpcb** [comment]
Thank you, I'm looking forward to this!

It would be great if you add the USB and LDO to the PCB files in this repository. You can place the components at any location you want, and I would move them to another location if necessary.

(Same for the Addressable RGB LEDs from issue #2.)

That would be very helpful for seeing what should be connected to what correctly. Thanks!

**Comment by Gondolindrim** [comment]
The problem with this whole discussion, from a documentation standpoint, is that the compartmentalization of information is made difficult if I try to add a "features" section. I will see what I can do; in the meantime, please look at the [Athena PCB](https://github.com/AcheronProject/Athena) for design reference.

**Comment by rgbpcb** [comment]
> The problem with this whole discussion, from a documentation standpoint, is that the compartmentalization of information is made difficult if I try to add a "features" section. I will see what I can do

In the documentation, you could write something like _"The Joker PCB files contain a USB connector for your convenience. Feel free to move it to a different location on the PCB, but make sure to route the differential pair carefully, as described [here](http://acheronproject.com/acheron_setup/acheron_setup/#33-overall-design-recommendations)."_

Does that seem good, or what information is problematic?

**Comment by Gondolindrim** [comment]
Well, the Joker implementation itself is not particularly problematic; rather, the integration of keyboard features into Joker's documentation.

However I do feel that these features are important. I will try adding them later.
