### ISSUE TITLE
Multiple issues with footprint library names

### ISSUE THREAD

**Issue by Razerban** [AcheronProject/AcheronSetup#6]
The foorprint library names generated by the script and written to the final `fp-lib-table` point to the wrong paths and aren't the same as the ones used in the template KiCad projects:

This is the content of the `fp-lib-table` generated by the script with the following arguments: `-p test -s MX_soldermask -t J64`:
```lisp
(fp_lib_table
(lib (name "acheron_3D.pretty")(type "KiCad")(uri "${KIPRJMOD}/libraries/acheron_3D.pretty.pretty")(options "")(descr "Acheron Project footprint library"))
(lib (name "acheron_Logo.pretty")(type "KiCad")(uri "${KIPRJMOD}/libraries/acheron_Logo.pretty.pretty")(options "")(descr "Acheron Project footprint library"))
(lib (name "acheron_Graphics.pretty")(type "KiCad")(uri "${KIPRJMOD}/libraries/acheron_Graphics.pretty.pretty")(options "")(descr "Acheron Project footprint library"))
(lib (name "acheron_MX_soldermask.pretty")(type "KiCad")(uri "${KIPRJMOD}/libraries/acheron_MX_soldermask.pretty.pretty")(options "")(descr "Acheron Project footprint library"))
(lib (name "acheron_Hardware.pretty")(type "KiCad")(uri "${KIPRJMOD}/libraries/acheron_Hardware.pretty.pretty")(options "")(descr "Acheron Project footprint library"))
(lib (name "acheron_Connectors.pretty")(type "KiCad")(uri "${KIPRJMOD}/libraries/acheron_Connectors.pretty.pretty")(options "")(descr "Acheron Project footprint library"))
(lib (name "acheron_Components.pretty")(type "KiCad")(uri "${KIPRJMOD}/libraries/acheron_Components.pretty.pretty")(options "")(descr "Acheron Project footprint library"))
)
```
1. Notice the extra `.pretty` in the path provided for the `uri` property in each line.
2. The footprints assigned to the symbols in the schematic file of the template KiCad projects point to footprints in libraries not ending with `.pretty`: e.g

![image](https://user-images.githubusercontent.com/7271421/151131429-a8429026-d976-4619-828f-a6143c03b3a1.png)

Also, I noticed a typo in the name of the logos footprint library: should be [`acheron_Logos.pretty`](https://github.com/AcheronProject/acheron_Logos.pretty) and not `acheron_logo.pretty`.

I have created a PR (https://github.com/AcheronProject/AcheronSetup/pull/7) to fix these issues.

**Comment by Gondolindrim** [comment]
This has been fixed in https://github.com/AcheronProject/AcheronSetup/pull/7 .
