### ISSUE TITLE
Symbol STM32F411-48 used in the joker48_template project but not found in acheron_Symbol

### ISSUE THREAD

**Issue by Razerban** [AcheronProject/AcheronSetup#8]
The symbol `STM32F411-48` is used in the joker48_template project but is not found in `acheron_Symbols` symbol library.

It's still defined in the schematic file:
https://github.com/AcheronProject/AcheronSetup/blob/38a441b03cf2d87f9b84fae42a58691b0dbfa74a/keyboard_creator/joker48_template/joker48.kicad_sch#L425-L895
 
But when I try to update the symbols from the library, I get the following error:
![image](https://user-images.githubusercontent.com/7271421/151189436-0f85e285-ca0c-49ef-9803-93892ee8f1ef.png)

I think that the template project has been created with an old revision of the `acheron_Symbols` library which had the symbol `STM32F411-48` in it and KiCad copied the symbol definition when it was placed to the schematic file.

**Comment by Gondolindrim** [comment]
Hi @Razerban 

The template does not feature any libraries, symbols or footprints, because the script will add those later.

**Comment by Razerban** [comment]
> Hi @Razerban
> 
> The template does not feature any libraries, symbols or footprints, because the script will add those later.

Hey @Gondolindrim!

That's true. The project is after all a template and the libraries would be added by the script.

However, even when using the script to download the libraries (symbols and footprints), the problem persists because the symbol `STM32F411-48` isn't present in the downloaded symbols library `acheron_Symbols`.

![image](https://user-images.githubusercontent.com/7271421/151960548-c1b62570-2f50-476c-bd89-9d4dffef6d00.png)

**Comment by Gondolindrim** [comment]
Hi @Razerban , 

If you take a close look, the footprint used is `STM_UFQFPN-48_LQFP-48-1EP_7x7mm_P0.5mm_HandSoldering_ThermalReliefs`

![image](https://user-images.githubusercontent.com/39470766/151988325-b3800efc-d738-4e2f-a31c-dc843a7ebf63.png)
