### ISSUE TITLE
Wrong schematic and PCB for project joker64_template project

### ISSUE THREAD

**Issue by Razerban** [AcheronProject/AcheronSetup#9]
The schematic file of the joker64_template project contains 4 copies of the STM32F411-48 symbol:

<img width="1038" alt="Screenshot 2022-01-26 at 16 20 54" src="https://user-images.githubusercontent.com/7271421/151192551-1708ce96-22a0-4ca0-bcb1-9e4f52951b71.png">
 
The PCB template seems to be the same for both of the `joker48_template` and the `joker64_template` projects:

![image](https://user-images.githubusercontent.com/7271421/151193746-4b760471-f818-44b5-8367-76f16372cb59.png)

**Comment by Gondolindrim** [comment]
Hey!

The Joker64 template as well as the documentation is still under construction. I want to get the script perfect so we can work on the templates and a front-end GUI!
